onboarding = false

[keys]
next_tab = "ctrl+cmd+backtick"

[ui.toast]
delivery = "system"

[ui]
show_agent_labels_on_pane_borders = true

[[keys.command]]
key = "ctrl+backtick"
type = "shell"
command = "~/.config/herdr/scripts/split-vim-above.js"
